# DevMate 配置文件

[model]
ai_base_url = "http://localhost:11434"
api_key = "ollama"
model_name = "qwen2.5:7b-instruct"
embedding_model_name = "nomic-embed-text"

[search]
tavily_api_key = "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"

[langsmith]
langchain_tracing_v2 = true
langchain_api_key = "your_langchain_api_key_here"

[skills]
skills_dir = "./skills"
