# Auto generated by DevMate
import logging

from devmate.agent.executor import executor_loop


def main() -> None:
    logging.basicConfig(
        level=logging.INFO,
        format="%(asctime)s | %(levelname)s | %(name)s | %(message)s",
    )
    executor_loop()


if __name__ == "__main__":
    main()