import json
import logging
from pathlib import Path

from devmate.agent.runtime import run_agent

logger = logging.getLogger(__name__)

PROJECT_ROOT = Path(__file__).resolve().parents[3]


def save_generated_files(plan: dict):

    files = plan.get("files_to_create", [])

    for file in files:
        file_path = PROJECT_ROOT / file
        file_path.parent.mkdir(parents=True, exist_ok=True)

        with open(file_path, "w", encoding="utf-8") as f:
            f.write("# Auto generated by DevMate\n")

        logger.info("Created file: %s", file_path)


def executor_loop():

    goal = input("What do you want to build?\n> ")

    logger.info("Agent runtime started")

    # ⭐⭐⭐⭐⭐ 关键变化：这里不再自己做 planning
    plan = run_agent(goal)

    logger.info("Final plan ready")
    logger.debug("Plan detail: %s", json.dumps(plan))

    save_generated_files(plan)

    logger.info("Task finished successfully")


if __name__ == "__main__":

    logging.basicConfig(
        level=logging.INFO,
        format="%(asctime)s | %(levelname)s | %(name)s | %(message)s",
    )

    executor_loop()